id: AFD9D3406
title: 'Wisdom Essence of the Mighty One: A Daily Practice of Hayagrīva''s Play of
  the Three Realms, from the Ocean of Gathered Teachings of the Awesome Ones'
type: translation
pechas:
- I801E2060
- IE8E3C6E4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:39:13.281725
  last_modified_at: 2023-01-04 11:39:13.281731
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I801E2060/6FA3: '5900'
  IE8E3C6E4/088E: '5900'
